import type { EventSummary } from "../../contracts/src/index";

export const eventFixtures: EventSummary[] = [
  {
    id: "evt-frontend-accessible-ui",
    title: "台北前端可及性實作工作坊",
    summary: "從語意化 HTML、鍵盤操作到表單錯誤提示，實作可被人類與 Agent 都理解的活動頁面。",
    startsAt: "2026-07-04T09:30:00+08:00",
    endsAt: "2026-07-04T12:30:00+08:00",
    location: "taipei",
    locationLabel: "台北",
    venue: "松山文創園區共學教室",
    price: "free",
    priceLabel: "免費",
    category: "frontend",
    categoryLabel: "Frontend",
    level: "beginner",
    levelLabel: "入門",
    remainingCapacity: 18,
    featured: true,
    detailUrl: "/events/evt-frontend-accessible-ui"
  },
  {
    id: "evt-backend-api-contract",
    title: "新北 API Contract 設計夜",
    summary: "用 TypeScript DTO 與驗證規則設計可維護的查詢 API，避免前後端語意漂移。",
    startsAt: "2026-07-05T19:00:00+08:00",
    endsAt: "2026-07-05T21:00:00+08:00",
    location: "new_taipei",
    locationLabel: "新北",
    venue: "板橋共享辦公室 3F",
    price: "paid",
    priceLabel: "NT$ 450",
    category: "backend",
    categoryLabel: "Backend",
    level: "intermediate",
    levelLabel: "中階",
    remainingCapacity: 12,
    featured: true,
    detailUrl: "/events/evt-backend-api-contract"
  },
  {
    id: "evt-ai-agent-ready-intro",
    title: "線上 Agent-ready 網站入門",
    summary: "認識 WebMCP、Declarative Tool 與人類可控的 Agent 輔助流程。",
    startsAt: "2026-07-06T20:00:00+08:00",
    endsAt: "2026-07-06T21:30:00+08:00",
    location: "online",
    locationLabel: "線上",
    venue: "線上直播",
    price: "free",
    priceLabel: "免費",
    category: "ai",
    categoryLabel: "AI",
    level: "beginner",
    levelLabel: "入門",
    remainingCapacity: 80,
    featured: true,
    detailUrl: "/events/evt-ai-agent-ready-intro"
  },
  {
    id: "evt-devops-observability",
    title: "台中 DevOps 觀測性半日營",
    summary: "從 health check、log context 到煙霧測試，建立可診斷的活動平台。",
    startsAt: "2026-07-11T13:30:00+08:00",
    endsAt: "2026-07-11T17:00:00+08:00",
    location: "taichung",
    locationLabel: "台中",
    venue: "台中軟體園區 A 棟",
    price: "paid",
    priceLabel: "NT$ 900",
    category: "devops",
    categoryLabel: "DevOps",
    level: "intermediate",
    levelLabel: "中階",
    remainingCapacity: 22,
    featured: false,
    detailUrl: "/events/evt-devops-observability"
  },
  {
    id: "evt-security-tool-boundary",
    title: "高雄 Tool 邊界與安全設計",
    summary: "用實務案例討論搜尋、收藏、報名工具的權限分層與使用者確認點。",
    startsAt: "2026-07-12T10:00:00+08:00",
    endsAt: "2026-07-12T15:30:00+08:00",
    location: "kaohsiung",
    locationLabel: "高雄",
    venue: "亞灣新創園",
    price: "paid",
    priceLabel: "NT$ 1,200",
    category: "security",
    categoryLabel: "Security",
    level: "advanced",
    levelLabel: "進階",
    remainingCapacity: 9,
    featured: true,
    detailUrl: "/events/evt-security-tool-boundary"
  },
  {
    id: "evt-data-sqlite-seed",
    title: "線上 SQLite Seed 資料設計",
    summary: "用固定 seed 資料支援文章截圖、測試與可重現 demo。",
    startsAt: "2026-07-13T19:30:00+08:00",
    endsAt: "2026-07-13T21:00:00+08:00",
    location: "online",
    locationLabel: "線上",
    venue: "線上會議室",
    price: "free",
    priceLabel: "免費",
    category: "data",
    categoryLabel: "Data",
    level: "beginner",
    levelLabel: "入門",
    remainingCapacity: 60,
    featured: false,
    detailUrl: "/events/evt-data-sqlite-seed"
  },
  {
    id: "evt-frontend-form-semantics",
    title: "新北語意化表單設計實戰",
    summary: "把搜尋條件、label、name 與欄位說明整理成穩定的 Declarative Tool 輸入。",
    startsAt: "2026-07-18T14:00:00+08:00",
    endsAt: "2026-07-18T16:30:00+08:00",
    location: "new_taipei",
    locationLabel: "新北",
    venue: "新店工程師社群空間",
    price: "free",
    priceLabel: "免費",
    category: "frontend",
    categoryLabel: "Frontend",
    level: "intermediate",
    levelLabel: "中階",
    remainingCapacity: 25,
    featured: false,
    detailUrl: "/events/evt-frontend-form-semantics"
  },
  {
    id: "evt-backend-express-minimal",
    title: "台北 Express API 最小可行架構",
    summary: "建立健康檢查、查詢參數驗證與可測試的搜尋服務。",
    startsAt: "2026-07-19T09:30:00+08:00",
    endsAt: "2026-07-19T12:00:00+08:00",
    location: "taipei",
    locationLabel: "台北",
    venue: "台北科技聚落 2F",
    price: "paid",
    priceLabel: "NT$ 600",
    category: "backend",
    categoryLabel: "Backend",
    level: "beginner",
    levelLabel: "入門",
    remainingCapacity: 16,
    featured: false,
    detailUrl: "/events/evt-backend-express-minimal"
  },
  {
    id: "evt-ai-ui-feedback",
    title: "台中 Agent 執行狀態 UI 設計",
    summary: "設計 toolactivated、toolcancel 與搜尋完成時的可見回饋。",
    startsAt: "2026-07-20T18:30:00+08:00",
    endsAt: "2026-07-20T20:30:00+08:00",
    location: "taichung",
    locationLabel: "台中",
    venue: "中區共同工作空間",
    price: "free",
    priceLabel: "免費",
    category: "ai",
    categoryLabel: "AI",
    level: "intermediate",
    levelLabel: "中階",
    remainingCapacity: 30,
    featured: false,
    detailUrl: "/events/evt-ai-ui-feedback"
  },
  {
    id: "evt-devops-playwright-smoke",
    title: "線上 Playwright Smoke Test 小聚",
    summary: "用 desktop 與 mobile 煙霧測試檢查首頁、搜尋結果與診斷頁。",
    startsAt: "2026-07-21T20:00:00+08:00",
    endsAt: "2026-07-21T21:30:00+08:00",
    location: "online",
    locationLabel: "線上",
    venue: "線上直播",
    price: "free",
    priceLabel: "免費",
    category: "devops",
    categoryLabel: "DevOps",
    level: "beginner",
    levelLabel: "入門",
    remainingCapacity: 95,
    featured: false,
    detailUrl: "/events/evt-devops-playwright-smoke"
  },
  {
    id: "evt-security-prompt-injection",
    title: "台北 Prompt Injection 威脅建模",
    summary: "從活動描述、第三方內容與工具輸入討論 Agent-ready 網站的基本防護。",
    startsAt: "2026-07-25T13:00:00+08:00",
    endsAt: "2026-07-25T17:00:00+08:00",
    location: "taipei",
    locationLabel: "台北",
    venue: "信義開發者基地",
    price: "paid",
    priceLabel: "NT$ 1,500",
    category: "security",
    categoryLabel: "Security",
    level: "advanced",
    levelLabel: "進階",
    remainingCapacity: 6,
    featured: false,
    detailUrl: "/events/evt-security-prompt-injection"
  },
  {
    id: "evt-data-search-quality",
    title: "高雄搜尋品質與資料標記",
    summary: "設計搜尋欄位、分類、難度與費用資料，讓結果更容易被篩選與解釋。",
    startsAt: "2026-07-26T10:00:00+08:00",
    endsAt: "2026-07-26T12:00:00+08:00",
    location: "kaohsiung",
    locationLabel: "高雄",
    venue: "高雄數位內容中心",
    price: "free",
    priceLabel: "免費",
    category: "data",
    categoryLabel: "Data",
    level: "intermediate",
    levelLabel: "中階",
    remainingCapacity: 28,
    featured: false,
    detailUrl: "/events/evt-data-search-quality"
  }
];
